cache:
  backend: "memory"
  default_ttl: 3600  # 1 hour in seconds
  memory:
    cleanup_interval: 600  # cleanup every 10 minutes
  redis:
    address: "localhost:6379"
    password: ""
    db: 0
    max_retries: 3
    pool_size: 10

httpserver:
  port: 8080
  host: "localhost"

chimux:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]