scheduler:
  worker_pool_size: 5
  max_concurrent_jobs: 10
  job_timeout: 300  # 5 minutes in seconds
  enable_persistence: false
  history_retention: 168  # 7 days in hours

httpserver:
  port: 8080
  host: "localhost"

chimux:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]