# Instance-Aware Database Configuration Example
# This example demonstrates instance-aware environment variable configuration
# The YAML values below are overridden by DB_*_* environment variables set in main.go

# Basic application settings
database:
  default: "primary"
  connections:
    primary:
      driver: ""  # Will be overridden by DB_PRIMARY_DRIVER env var 
      dsn: ""     # Will be overridden by DB_PRIMARY_DSN env var
    secondary:
      driver: ""  # Will be overridden by DB_SECONDARY_DRIVER env var
      dsn: ""     # Will be overridden by DB_SECONDARY_DSN env var
    cache:
      driver: ""  # Will be overridden by DB_CACHE_DRIVER env var
      dsn: ""     # Will be overridden by DB_CACHE_DSN env var